-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.curve("overshot", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.curve("smoothOut", { type = "bezier", points = { { 0.36, 0 }, { 0.66, -0.56 } } })
hl.curve("smoothIn", { type = "bezier", points = { { 0.25, 1 }, { 0.5, 1 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 3,
    bezier = "overshot",
    style = "slide",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 2,
    bezier = "smoothOut",
    style = "slide",
})
hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 3,
    bezier = "default",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 10,
    bezier = "smoothIn",
})
hl.animation({
    leaf = "fadeDim",
    enabled = true,
    speed = 10,
    bezier = "smoothIn",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 6,
    bezier = "default",
})

hl.config({
    general = {
        gaps_in = 2,
        gaps_out = 2,
        border_size = 2,
        col = {
            active_border = { colors = { "rgba(00c8ffee)", "rgba(00ffffee)", "rgba(00ffccee)", "rgba(00ff00ee)", "rgba(ffff00ee)", "rgba(ffc800ee)", "rgba(ff0000ee)" }, angle = 40 },
            inactive_border = "rgba(4b4b4bee)",
            nogroup_border = "rgba(ff0000ee)",
            nogroup_border_active = "rgba(4b4b4bee)",
        },
        layout = "dwindle",
        snap = {
            enabled = true,
            window_gap = 10,
            monitor_gap = 10,
            border_overlap = false,
            respect_gaps = true,
        },
    },
    debug = {
        disable_logs = true,
    },
    group = {
        insert_after_current = true,
        focus_removed_window = true,
        merge_groups_on_drag = true,
        col = {
            border_active = { colors = { "rgba(00c8ffee)", "rgba(00ffffee)", "rgba(00ffccee)", "rgba(00ff00ee)", "rgba(ffff00ee)", "rgba(ffc800ee)", "rgba(ff0000ee)" }, angle = 40 },
            border_inactive = "rgba(4b4b4bee)",
            border_locked_active = "rgba(66777799)",
            border_locked_inactive = "rgba(66775599)",
        },
        groupbar = {
            enabled = true,
            font_family = "misc:font_family",
            font_size = 8,
            gradients = true,
            height = 14,
            stacked = false,
            priority = 3,
            render_titles = true,
            scrolling = true,
            text_color = "rgba(ffffffff)",
            col = {
                active = "rgba(66ffff55)",
                inactive = "rgba(4b4b4bee)",
                locked_active = "rgba(66777799)",
                locked_inactive = "rgba(66775599)",
            },
        },
    },
    misc = {
        background_color = "rgb(000000)",
        force_default_wallpaper = -1,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
        focus_on_activate = false,
        mouse_move_focuses_monitor = true,
        vrr = 2,
        enable_swallow = true,
        swallow_regex = "^(kitty|nautilus)$",
    },
    -- TODO: Test HDR later
    render = {
        cm_enabled = true, -- bool, defaults to true even unset
        send_content_type = true, -- bool, defaults to true even unset
        cm_auto_hdr = 1, -- int, defaults to 1 (on) even unset. 1 = auto-switch monitor cm
    --                      -- to "hdr" on fullscreen, 2 = same but to "hdredid". Leave at 0 if
    --                      -- any monitor uses a custom cm (dcip3/wide/hdr/etc), since the
    --                      -- auto-toggle doesn't restore it correctly on exit from fullscreen
    --                      -- HDR content, see Hyprland issue #12971.
    --     non_shader_cm = 3, -- int, default; 3 = never allow CM without a shader pass (safest,
    --                        -- but blocks direct scanout in some fullscreen cases); 1/2 loosen
    --                        -- that at some color-correctness risk, exact difference between
    --                        -- them isn't documented anywhere as of Hyprland 0.56.
    --     cm_sdr_eotf = "default", -- string, not a number: "default" | "srgb" | "gamma22"
    -- },
    -- quirks = {
    --     prefer_hdr = 0, -- int, default 0. Forces the monitor into HDR before a window opens,
    --                     -- for apps that expect HDR already active (cm_auto_hdr only reacts
    --                     -- after fullscreen is detected, which is too late for those and
    --                     -- causes a white flash). Whether values >1 mirror cm_auto_hdr's
    --                     -- hdr/hdredid split isn't confirmed.
    },
    decoration = {
        rounding = 8,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        blur = {
            enabled = true,
            size = 1,
            passes = 2,
            new_optimizations = true,
            xray = false,
            ignore_opacity = false,
            vibrancy = 1,
            vibrancy_darkness = 1,
            popups = true,
        },
        shadow = {
            enabled = false,
            range = 4,
            render_power = 2,
            sharp = true,
            color = 0xee1a1a1a,
            color_inactive = 0xeeff0000,
            offset = "2 2",
            scale = 1,
        },
    },
    animations = {
        enabled = true,
    },
    dwindle = {
        preserve_split = true, -- you probably want this
        use_active_for_splits = false,
        smart_split = true,
    },
})

