windowrule {
  name = VideoBridge-Float-Center
  opacity = 0.0 override
  no_anim = on
  no_initial_focus = on
  max_size = 1 1
  no_blur = on
  no_focus = on
  match:class = ^(xwaylandvideobridge)$
}

windowrule {
  name = Qalculate-Float-Center
  size = 400 400
  center = on
  float = on
  match:title = (Qalculate!)$
}

windowrule {
  name = Calculator-Float-Center
  size = 400 620
  center = on
  float = on
  match:initial_class = (org.gnome.Calculator)$
}

windowrule {
  name = Xsensors-Float-Center
  size = 610 610
  center = on
  float = on
  match:initial_class = (xsensors)$
}

windowrule {
  name = Calendar-Float-Center
  size = 400 600
  center = on
  float = on
  match:class = (org.gnome.Calendar)$
}

windowrule {
  name = Volume-Float-Center
  float = on
  center = center
  size = 1500 900
  match:title = ^(Volume Control)$
}

windowrule {
  name = Blueman-Float-Center
  float = on
  center = center
  size = 1500 900
  match:class = ^(blueman-manager)$
}

windowrule {
  name = Network-Float-Center
  float = on
  center = center
  size = 800 900
  match:class = ^(nm-connection-editor)$
}

windowrule {
  name = Kyitty-Animation
  animation = fade
  match:class = kitty
}

windowrule {
  name = FullScreen-Border
  border_color = rgba(FF0000FF) rgba(880808FF)
  match:fullscreen = 1
}

windowrule {
  name = Hyperland-Border
  border_color = rgba(FFFF00FF) rgba(880808FF)
  match:title = ^(.*hyprland.*|.*Hyprland.*)$
}

windowrule {
  name = Float-Border
  border_color = rgba(FF0000FF) rgba(FF8888AA)
  match:float = 1
}

windowrule {
  name = JetBrains-Focus
  border_color = rgba(FF00FFFF) rgba(FF8888AA)
  match:class = jetbrains-idea
  match:float = on
}

windowrule {
  name = JetBrains-NoFocus
  no_initial_focus = on
  animation = fade
  match:class = jetbrains-idea
  match:title = ^(.*win.*)$
}

windowrule {
  name = JetBrains-Focus
  stay_focused = on
  match:class = jetbrains-idea
  match:title = (^$)
}

windowrule {
  name = Satty-Rule
  float = on
  center = on
  animation = fade
  stay_focused = on
  match:class = (com.gabm.satty)
  match:title = (satty)
}

windowrule {
  name = Karma-Rule
  float = on
  center = off
  animation = fade
  match:class = microsoft-edge
  match:title = ^(Karma - Work*)$
}

